version: '3.8'
services: 

    main:
        build: 
            context: .
            dockerfile: Dockerfile
        command: bash -c 'php artisan migrate && php artisan serve --host=0.0.0.0'
        volumes:
            - .:/app
        ports:
            - 8000:8000
        depends_on:
            -   db

    queue:
        build: 
            context: .
            dockerfile: Dockerfile
        command: 'php artisan queue:work'
        depends_on: 
            - db   

            
    db:
        platform: linux/x86_64
        image: mysql:8.0
        environment: 
            MYSQL_DATABASE: tradehub
            MYSQL_USER: admin
            MYSQL_PASSWORD: root
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./storage/dbdata:/var/lib/mysql
        ports:
            - 3307:3306     

